Update awake_start
Fixed syntax errors.

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -18,8 +18,6 @@ else
           -H "User-Agent: github.com/marcone/teslausb" \
           "https://api.tessie.com/$TESSIE_VIN/command/close_charge_port")
 
-        #log "Tessie: Nudging the car." #commented out to reduce log spam
-
         #Extract HTTP status code
         http_status="${http_response: -3}"
         
@@ -42,30 +40,25 @@ else
       fi
 
       if [[ -n "${TESLA_BLE_VIN:+x}" ]]
-      #Use Tesla BLE API to nudge the car
+      #use Tesla BLE API to nudge the car
       then
-        if BLE_response=$(/root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" charge-port-close 2>&1)
+        if ! BLE_response=$(/root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" charge-port-close 2>&1)
         then
-          #BLE success
-          #log "Tesla BLE: Successfully nudged the car to stay awake." #commented out to reduce log spam
-
-        elif [[ ( "$BLE_response" == *"already closed"* ) || ( "$BLE_response" == *"cable connected"* ) ]]
-          #Acceptable false-negative BLE responses
+          #check false-negative BLE responses
+          if [[ ( "$BLE_response" != *"already closed"* ) && ( "$BLE_response" != *"cable connected"* ) ]]
           then
-          log "Tesla BLE: Successfully nudged the car to stay awake."
-        
-        else  
-          #Log error and retry
-          log "Tesla BLE: Failed to nudge the car. There may be an issue with the BLE communication."
-          if [ "$retry" -lt "3" ]
-          then
-            log "Tesla BLE: Retrying after 30s in case the connection was poor."
-            retry=$((retry+1))
-            sleep 30
-            continue
-          else
-            log "Tesla BLE: $BLE_response"
-            break
+            #log error and retry
+            log "Tesla BLE: Failed to nudge the car. There may be an issue with the BLE communication."
+            if [ "$retry" -lt "3" ]
+            then
+              log "Tesla BLE: Retrying after 30s in case the connection was poor."
+              retry=$((retry+1))
+              sleep 30
+              continue
+            else
+              log "Tesla BLE: $BLE_response"
+              break
+            fi
           fi
         fi
       fi
